seed: 1
batch_size: 128
epochs: 10
lr: 0.01
embed: 256
hidden: 512
resnet: resnet50
vt: 5
num_layers: 1
save_every: 1
print_every: 100
categories:
    - bottle
    - bus
    - couch
    - microwave
    - pizza
    - racket
    - suitcase
    - zebra
